name: Release
on:
  workflow_dispatch:
    # push:
    #   branches:
    #     - main

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install -g semantic-release \
            @semantic-release/exec \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/changelog \
            @semantic-release/github \
            @semantic-release/git

      - name: Run Semantic Release
        id: release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next release version
        id: get_version
        run: |
          VERSION=$(npx semantic-release --dry-run | grep "The next release version is" | awk '{print $6}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create release branch
        if: success()
        run: |
          BRANCH_NAME="release/v$VERSION"
          git checkout main
          git pull origin main
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
